<?php
/**
 * Plugin Name: Tarot Reader
 * Description: Display tarot card readings (1, 3, or 7 cards) via shortcode [tarot_reader cards="1"].
 * Version: 1.0.0
 * Author: AutoGenerated
 */

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

function tarot_reader_get_cards() {
    return [
        ['name' => 'The Fool', 'meaning' => 'New beginnings, spontaneity, free spirit'],
        ['name' => 'The Magician', 'meaning' => 'Manifestation, resourcefulness, power'],
        ['name' => 'The High Priestess', 'meaning' => 'Intuition, mystery, subconscious mind'],
        ['name' => 'The Empress', 'meaning' => 'Femininity, beauty, nature, nurturing'],
        ['name' => 'The Emperor', 'meaning' => 'Authority, structure, control'],
        ['name' => 'The Hierophant', 'meaning' => 'Tradition, conformity, morality'],
        ['name' => 'The Lovers', 'meaning' => 'Love, harmony, relationships'],
        ['name' => 'The Chariot', 'meaning' => 'Direction, control, willpower'],
        ['name' => 'Strength', 'meaning' => 'Courage, persuasion, influence'],
        ['name' => 'The Hermit', 'meaning' => 'Soul-searching, introspection, solitude'],
        ['name' => 'Wheel of Fortune', 'meaning' => 'Change, cycles, fate'],
        ['name' => 'Justice', 'meaning' => 'Fairness, truth, law'],
        ['name' => 'The Hanged Man', 'meaning' => 'Pause, surrender, letting go'],
        ['name' => 'Death', 'meaning' => 'Endings, change, transformation'],
        ['name' => 'Temperance', 'meaning' => 'Balance, moderation, patience'],
        ['name' => 'The Devil', 'meaning' => 'Shadow self, attachment, restriction'],
        ['name' => 'The Tower', 'meaning' => 'Sudden change, upheaval'],
        ['name' => 'The Star', 'meaning' => 'Hope, faith, renewal'],
        ['name' => 'The Moon', 'meaning' => 'Illusion, fear, anxiety'],
        ['name' => 'The Sun', 'meaning' => 'Positivity, fun, warmth'],
        ['name' => 'Judgment', 'meaning' => 'Reflection, reckoning'],
        ['name' => 'The World', 'meaning' => 'Completion, accomplishment, travel'],
    ];
}

function tarot_reader_draw($count = 1) {
    $cards = tarot_reader_get_cards();
    shuffle($cards);
    return array_slice($cards, 0, $count);
}

function tarot_reader_shortcode($atts) {
    $atts = shortcode_atts(['cards' => 1], $atts, 'tarot_reader');
    $count = intval($atts['cards']);
    if (!in_array($count, [1,3,7])) {
        $count = 1;
    }
    $drawn = tarot_reader_draw($count);
    ob_start();
    echo '<div class="tarot-reading">';
    foreach ($drawn as $card) {
        echo '<div class="tarot-card">';
        echo '<strong>' . esc_html($card['name']) . '</strong><br />';
        echo '<em>' . esc_html($card['meaning']) . '</em>';
        echo '</div>';
    }
    echo '</div>';
    return ob_get_clean();
}
add_shortcode('tarot_reader', 'tarot_reader_shortcode');

